# Conexión a MariaDB
spring.datasource.url=jdbc:mariadb://localhost:3306/otec_admin_db
spring.datasource.username=app_user
spring.datasource.password=123456
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

# Configuración de Hibernate (Mantenemos update por ahora en desarrollo local)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true